### ISSUE TITLE
No mention of enterprise architecture

### ISSUE THREAD

**Issue by bgea** [WhiteHouse/fitara#22]
FITARA, while providing the CIO with more power over the IT portfolio, does not mention or recommend the use of enterprise architecture (FEAFv2) as an essential component of the CIO's decision-making arsenal of tools, particularly utilizing the business architecture, in order to ensure business needs are prioritized in such a way to deliver value to the organization.  Often times, CIOs become consumed by tactical needs of the infrastructure and solution architecture decisions and activities, while the business needs may not be as apparent without EA articulating the business alignment that is supported by the IT investments in the portfolio.

**Comment by bradshawll** [comment]
Can a value proposition be required for all expenditures, with some way to identify exactly how the results or product of the expenditure fulfills the proposition or delivers value?  Or perhaps a value-chain and product-chain underpinning the common baseline and also posted for public review and comment, or academic study?  

Speaking of value, product, and supply chains, these are not unique or limited to IT.  What does FITARA do to encourage business management that uses these tools, publishes these items?  Can IT realistically be optimized if, in fact, the business overall has not been optimized?  Or, can a Common Baseline for IT exist in the absense of a Common Baseline for the entire business, Department, or Agency?  Isn't the concept that IT is business and business is IT a core principle, and driver, behind FITARA?  As two sides of one coin, requiring an IT specific Common Baseline seems to be less than ideal; shouldn't the IT specific Common Baseline be hardwired into the overall Organization Common Baseline?  To put this a different way, if the business doesn't know what it needs, wants, or will value in six months, how can a CIO plan three years ahead and provide a viable, well documented, concise, and accurate IT specific Common Baseline?

Some very senior managers are highly results oriented and solutions focussed.  So much so that they will knowlingly dual or tripple track efforts, allowing whichever group delivers the most value first to subsume the other groups.  While the wasted effort may make sense in some conditions or circumstances, this is not a common practice in my experience in the commercial world.  How does FITARA ensure that dual or tripple tracking, or redundant and mostly identical efforts, are known and accounted for properly?

**Comment by arlotti-parish** [comment]
Enterprise Architecture (EA) wasn't mentioned in the FITARA legislation so it shouldn't be included in the instructions for implementing FITARA.  OMB has plenty of other guidance mechanisms available to give IT direction without expanding the scope of this document beyond meeting the new specific legal requirements of FITARA.  

I wholeheartedly agree that IT and it's leadership need strong mechanisms for identifying and fulfilling high value IT needs of the mission.

**Comment by bsweezy** [comment]
Thank you @bgea for your comments. As part of OMB's review of the public comments we have included "enterprise architecture" as a core component of the IT processes and policies for which the CIO is responsible. Please see "G1" in the Common Baseline, as follows: "G1. CIO Role/Responsibility: CIO defines IT processes and policies. The CIO defines the development processes, milestones, review gates, and the overall policies for all capital planning, enterprise architecture, and project management and reporting for IT resources..."
